pipeline {
    agent none
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post {
                always {
                    junit 'test-reports/results.xml'
                }
            }
        }
        stage('Deliver') {
            agent {
                docker {
                    image 'cdrx/pyinstaller-linux:python2'
                }
            }
            steps {
                sh 'pyinstaller --onefile sources/add2vals.py'
            }
            post {
                success {
                    archiveArtifacts 'dist/add2vals'
                }
            }
        }
    }
}

// jenkins docs
// pipeline {
//     agent none
//     stages {
//         stage('Build') {
//             agent {
//                 docker {
//                     image 'python:3.12.1-alpine3.19'
//                 }
//             }
//             steps {
//                 sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//                 stash(name: 'compiled-results', includes: 'sources/*.py*')
//             }
//         }
//         stage('Test') { 
//             agent {
//                 docker {
//                     image 'qnib/pytest' 
//                 }
//             }
//             steps {
//                 sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py' 
//             }
//             post {
//                 always {
//                     junit 'test-reports/results.xml' 
//                 }
//             }
//         }
//     }
// }

// withDockerContainer
// node {
//     withDockerContainer('python:3.12.1-alpine3.19') {
//         stage('Build') {
//             sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//             stash name: 'compiled-results', includes: 'sources/*.py*'
//         }
//     }
//     withDockerContainer('qnib/pytest') {
//         stage('Test') {
//             sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
//         }
//         post {
//             always {
//                 junit 'test-reports/results.xml'
//             }
//         }
//     }
// }

// docker.image
// A
// node {
//     docker.image('python:3.12.1-alpine3.19').inside {
//         stage('Build') {
//             sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//             stash name: 'compiled-results', includes: 'sources/*.py*'
//         }
//     }
//     docker.image('qnib/pytest').inside {
//         stage('Test') {
//             sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
//         }
//         post {
//             always {
//                 junit 'test-reports/results.xml'
//             }
//         }
//     }
// }

// B
// node {
//     checkout scm
//     docker.image('python:3.12.1-alpine3.19').inside {
//         stage('Build') {
//             sh 'python -m py_compile sources/add2vals.py sources/calc.py'
//         }
//     }
//     docker.image('qnib/pytest').inside {
//         stage('Test') {
//             sh 'py.test --junit-xml test-reports/results.xml sources/test_calc.py'
//         }
//     }
// }